// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: services/repo.proto

package services

import (
	packets "github.com/fatehan-navzy/strc/packets"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packet        *packets.Packet        `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Client        *packets.Client        `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_services_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_services_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_services_repo_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceStatus) GetPacket() *packets.Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *DeviceStatus) GetClient() *packets.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_services_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_services_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_services_repo_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_services_repo_proto protoreflect.FileDescriptor

const file_services_repo_proto_rawDesc = "" +
	"\n" +
	"\x13services/repo.proto\x12\x12com.navzy.services\x1a\x15packets/packets.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\fDeviceStatus\x121\n" +
	"\x06packet\x18\x01 \x01(\v2\x19.com.navzy.packets.PacketR\x06packet\x121\n" +
	"\x06client\x18\x02 \x01(\v2\x19.com.navzy.packets.ClientR\x06client\x12:\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03endBF\n" +
	"\x1acom.fatehan.navzy.servicesP\x01Z&github.com/fatehan-navzy/strc/servicesb\x06proto3"

var (
	file_services_repo_proto_rawDescOnce sync.Once
	file_services_repo_proto_rawDescData []byte
)

func file_services_repo_proto_rawDescGZIP() []byte {
	file_services_repo_proto_rawDescOnce.Do(func() {
		file_services_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_repo_proto_rawDesc), len(file_services_repo_proto_rawDesc)))
	})
	return file_services_repo_proto_rawDescData
}

var file_services_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_repo_proto_goTypes = []any{
	(*DeviceStatus)(nil),          // 0: com.navzy.services.DeviceStatus
	(*TimeRange)(nil),             // 1: com.navzy.services.TimeRange
	(*packets.Packet)(nil),        // 2: com.navzy.packets.Packet
	(*packets.Client)(nil),        // 3: com.navzy.packets.Client
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_services_repo_proto_depIdxs = []int32{
	2, // 0: com.navzy.services.DeviceStatus.packet:type_name -> com.navzy.packets.Packet
	3, // 1: com.navzy.services.DeviceStatus.client:type_name -> com.navzy.packets.Client
	4, // 2: com.navzy.services.DeviceStatus.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: com.navzy.services.TimeRange.start:type_name -> google.protobuf.Timestamp
	4, // 4: com.navzy.services.TimeRange.end:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_repo_proto_init() }
func file_services_repo_proto_init() {
	if File_services_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_repo_proto_rawDesc), len(file_services_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_repo_proto_goTypes,
		DependencyIndexes: file_services_repo_proto_depIdxs,
		MessageInfos:      file_services_repo_proto_msgTypes,
	}.Build()
	File_services_repo_proto = out.File
	file_services_repo_proto_goTypes = nil
	file_services_repo_proto_depIdxs = nil
}
