// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: services/services.proto

package services

import (
	devices "github.com/fatehan-navzy/strc/devices"
	packets "github.com/fatehan-navzy/strc/packets"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaticKeys    []string               `protobuf:"bytes,1,rep,name=static_keys,json=staticKeys,proto3" json:"static_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusRequest) Reset() {
	*x = DeviceStatusRequest{}
	mi := &file_services_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusRequest) ProtoMessage() {}

func (x *DeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*DeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceStatusRequest) GetStaticKeys() []string {
	if x != nil {
		return x.StaticKeys
	}
	return nil
}

type DeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          uint32                 `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Records       uint32                 `protobuf:"varint,2,opt,name=records,proto3" json:"records,omitempty"`
	List          []*DeviceStatus        `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusResponse) Reset() {
	*x = DeviceStatusResponse{}
	mi := &file_services_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusResponse) ProtoMessage() {}

func (x *DeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceStatusResponse) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *DeviceStatusResponse) GetRecords() uint32 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *DeviceStatusResponse) GetList() []*DeviceStatus {
	if x != nil {
		return x.List
	}
	return nil
}

type PacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *TimeRange             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StaticKey     []string               `protobuf:"bytes,2,rep,name=static_key,json=staticKey,proto3" json:"static_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest) Reset() {
	*x = PacketRequest{}
	mi := &file_services_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest) ProtoMessage() {}

func (x *PacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{2}
}

func (x *PacketRequest) GetTimestamp() *TimeRange {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PacketRequest) GetStaticKey() []string {
	if x != nil {
		return x.StaticKey
	}
	return nil
}

type PacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packets       []*packets.Packet      `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketResponse) Reset() {
	*x = PacketResponse{}
	mi := &file_services_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketResponse) ProtoMessage() {}

func (x *PacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketResponse.ProtoReflect.Descriptor instead.
func (*PacketResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{3}
}

func (x *PacketResponse) GetPackets() []*packets.Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

var File_services_services_proto protoreflect.FileDescriptor

const file_services_services_proto_rawDesc = "" +
	"\n" +
	"\x17services/services.proto\x12\x12com.navzy.services\x1a\x13services/repo.proto\x1a\x15devices/devices.proto\x1a\x15packets/packets.proto\"6\n" +
	"\x13DeviceStatusRequest\x12\x1f\n" +
	"\vstatic_keys\x18\x01 \x03(\tR\n" +
	"staticKeys\"z\n" +
	"\x14DeviceStatusResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\rR\x04cost\x12\x18\n" +
	"\arecords\x18\x02 \x01(\rR\arecords\x124\n" +
	"\x04list\x18\x03 \x03(\v2 .com.navzy.services.DeviceStatusR\x04list\"k\n" +
	"\rPacketRequest\x12;\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1d.com.navzy.services.TimeRangeR\ttimestamp\x12\x1d\n" +
	"\n" +
	"static_key\x18\x02 \x03(\tR\tstaticKey\"E\n" +
	"\x0ePacketResponse\x123\n" +
	"\apackets\x18\x01 \x03(\v2\x19.com.navzy.packets.PacketR\apackets2\x92\x02\n" +
	"\fNavzyService\x12T\n" +
	"\vPacketIndex\x12!.com.navzy.services.PacketRequest\x1a\".com.navzy.services.PacketResponse\x12D\n" +
	"\fDeviceCreate\x12\x19.com.navzy.devices.Device\x1a\x19.com.navzy.devices.Device\x12f\n" +
	"\x11DeviceStatusIndex\x12'.com.navzy.services.DeviceStatusRequest\x1a(.com.navzy.services.DeviceStatusResponseBF\n" +
	"\x1acom.fatehan.navzy.servicesP\x01Z&github.com/fatehan-navzy/strc/servicesb\x06proto3"

var (
	file_services_services_proto_rawDescOnce sync.Once
	file_services_services_proto_rawDescData []byte
)

func file_services_services_proto_rawDescGZIP() []byte {
	file_services_services_proto_rawDescOnce.Do(func() {
		file_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_services_proto_rawDesc), len(file_services_services_proto_rawDesc)))
	})
	return file_services_services_proto_rawDescData
}

var file_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_services_proto_goTypes = []any{
	(*DeviceStatusRequest)(nil),  // 0: com.navzy.services.DeviceStatusRequest
	(*DeviceStatusResponse)(nil), // 1: com.navzy.services.DeviceStatusResponse
	(*PacketRequest)(nil),        // 2: com.navzy.services.PacketRequest
	(*PacketResponse)(nil),       // 3: com.navzy.services.PacketResponse
	(*DeviceStatus)(nil),         // 4: com.navzy.services.DeviceStatus
	(*TimeRange)(nil),            // 5: com.navzy.services.TimeRange
	(*packets.Packet)(nil),       // 6: com.navzy.packets.Packet
	(*devices.Device)(nil),       // 7: com.navzy.devices.Device
}
var file_services_services_proto_depIdxs = []int32{
	4, // 0: com.navzy.services.DeviceStatusResponse.list:type_name -> com.navzy.services.DeviceStatus
	5, // 1: com.navzy.services.PacketRequest.timestamp:type_name -> com.navzy.services.TimeRange
	6, // 2: com.navzy.services.PacketResponse.packets:type_name -> com.navzy.packets.Packet
	2, // 3: com.navzy.services.NavzyService.PacketIndex:input_type -> com.navzy.services.PacketRequest
	7, // 4: com.navzy.services.NavzyService.DeviceCreate:input_type -> com.navzy.devices.Device
	0, // 5: com.navzy.services.NavzyService.DeviceStatusIndex:input_type -> com.navzy.services.DeviceStatusRequest
	3, // 6: com.navzy.services.NavzyService.PacketIndex:output_type -> com.navzy.services.PacketResponse
	7, // 7: com.navzy.services.NavzyService.DeviceCreate:output_type -> com.navzy.devices.Device
	1, // 8: com.navzy.services.NavzyService.DeviceStatusIndex:output_type -> com.navzy.services.DeviceStatusResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_services_proto_init() }
func file_services_services_proto_init() {
	if File_services_services_proto != nil {
		return
	}
	file_services_repo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_services_proto_rawDesc), len(file_services_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_services_proto_goTypes,
		DependencyIndexes: file_services_services_proto_depIdxs,
		MessageInfos:      file_services_services_proto_msgTypes,
	}.Build()
	File_services_services_proto = out.File
	file_services_services_proto_goTypes = nil
	file_services_services_proto_depIdxs = nil
}
