// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: services/services.proto

package services

import (
	context "context"
	devices "github.com/fatehan-navzy/strc/devices"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NavzyService_PacketIndex_FullMethodName       = "/com.navzy.services.NavzyService/PacketIndex"
	NavzyService_DeviceCreate_FullMethodName      = "/com.navzy.services.NavzyService/DeviceCreate"
	NavzyService_DeviceStatusIndex_FullMethodName = "/com.navzy.services.NavzyService/DeviceStatusIndex"
	NavzyService_DeviceImport_FullMethodName      = "/com.navzy.services.NavzyService/DeviceImport"
	NavzyService_DeviceExport_FullMethodName      = "/com.navzy.services.NavzyService/DeviceExport"
	NavzyService_Live_FullMethodName              = "/com.navzy.services.NavzyService/Live"
)

// NavzyServiceClient is the client API for NavzyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NavzyServiceClient interface {
	PacketIndex(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error)
	DeviceCreate(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error)
	DeviceStatusIndex(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatusResponse, error)
	DeviceImport(ctx context.Context, in *DeviceImportRequest, opts ...grpc.CallOption) (*DeviceImportResponse, error)
	DeviceExport(ctx context.Context, in *DeviceExportRequest, opts ...grpc.CallOption) (*DeviceExportResponse, error)
	Live(ctx context.Context, in *LiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStream], error)
}

type navzyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNavzyServiceClient(cc grpc.ClientConnInterface) NavzyServiceClient {
	return &navzyServiceClient{cc}
}

func (c *navzyServiceClient) PacketIndex(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PacketResponse)
	err := c.cc.Invoke(ctx, NavzyService_PacketIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navzyServiceClient) DeviceCreate(ctx context.Context, in *devices.Device, opts ...grpc.CallOption) (*devices.Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(devices.Device)
	err := c.cc.Invoke(ctx, NavzyService_DeviceCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navzyServiceClient) DeviceStatusIndex(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceStatusResponse)
	err := c.cc.Invoke(ctx, NavzyService_DeviceStatusIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navzyServiceClient) DeviceImport(ctx context.Context, in *DeviceImportRequest, opts ...grpc.CallOption) (*DeviceImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceImportResponse)
	err := c.cc.Invoke(ctx, NavzyService_DeviceImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navzyServiceClient) DeviceExport(ctx context.Context, in *DeviceExportRequest, opts ...grpc.CallOption) (*DeviceExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceExportResponse)
	err := c.cc.Invoke(ctx, NavzyService_DeviceExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navzyServiceClient) Live(ctx context.Context, in *LiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NavzyService_ServiceDesc.Streams[0], NavzyService_Live_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LiveRequest, LiveStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NavzyService_LiveClient = grpc.ServerStreamingClient[LiveStream]

// NavzyServiceServer is the server API for NavzyService service.
// All implementations must embed UnimplementedNavzyServiceServer
// for forward compatibility.
type NavzyServiceServer interface {
	PacketIndex(context.Context, *PacketRequest) (*PacketResponse, error)
	DeviceCreate(context.Context, *devices.Device) (*devices.Device, error)
	DeviceStatusIndex(context.Context, *DeviceStatusRequest) (*DeviceStatusResponse, error)
	DeviceImport(context.Context, *DeviceImportRequest) (*DeviceImportResponse, error)
	DeviceExport(context.Context, *DeviceExportRequest) (*DeviceExportResponse, error)
	Live(*LiveRequest, grpc.ServerStreamingServer[LiveStream]) error
	mustEmbedUnimplementedNavzyServiceServer()
}

// UnimplementedNavzyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNavzyServiceServer struct{}

func (UnimplementedNavzyServiceServer) PacketIndex(context.Context, *PacketRequest) (*PacketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PacketIndex not implemented")
}
func (UnimplementedNavzyServiceServer) DeviceCreate(context.Context, *devices.Device) (*devices.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCreate not implemented")
}
func (UnimplementedNavzyServiceServer) DeviceStatusIndex(context.Context, *DeviceStatusRequest) (*DeviceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceStatusIndex not implemented")
}
func (UnimplementedNavzyServiceServer) DeviceImport(context.Context, *DeviceImportRequest) (*DeviceImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceImport not implemented")
}
func (UnimplementedNavzyServiceServer) DeviceExport(context.Context, *DeviceExportRequest) (*DeviceExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceExport not implemented")
}
func (UnimplementedNavzyServiceServer) Live(*LiveRequest, grpc.ServerStreamingServer[LiveStream]) error {
	return status.Errorf(codes.Unimplemented, "method Live not implemented")
}
func (UnimplementedNavzyServiceServer) mustEmbedUnimplementedNavzyServiceServer() {}
func (UnimplementedNavzyServiceServer) testEmbeddedByValue()                      {}

// UnsafeNavzyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NavzyServiceServer will
// result in compilation errors.
type UnsafeNavzyServiceServer interface {
	mustEmbedUnimplementedNavzyServiceServer()
}

func RegisterNavzyServiceServer(s grpc.ServiceRegistrar, srv NavzyServiceServer) {
	// If the following call pancis, it indicates UnimplementedNavzyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NavzyService_ServiceDesc, srv)
}

func _NavzyService_PacketIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavzyServiceServer).PacketIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavzyService_PacketIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavzyServiceServer).PacketIndex(ctx, req.(*PacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavzyService_DeviceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavzyServiceServer).DeviceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavzyService_DeviceCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavzyServiceServer).DeviceCreate(ctx, req.(*devices.Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavzyService_DeviceStatusIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavzyServiceServer).DeviceStatusIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavzyService_DeviceStatusIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavzyServiceServer).DeviceStatusIndex(ctx, req.(*DeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavzyService_DeviceImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavzyServiceServer).DeviceImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavzyService_DeviceImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavzyServiceServer).DeviceImport(ctx, req.(*DeviceImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavzyService_DeviceExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavzyServiceServer).DeviceExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavzyService_DeviceExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavzyServiceServer).DeviceExport(ctx, req.(*DeviceExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavzyService_Live_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NavzyServiceServer).Live(m, &grpc.GenericServerStream[LiveRequest, LiveStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NavzyService_LiveServer = grpc.ServerStreamingServer[LiveStream]

// NavzyService_ServiceDesc is the grpc.ServiceDesc for NavzyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NavzyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.navzy.services.NavzyService",
	HandlerType: (*NavzyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PacketIndex",
			Handler:    _NavzyService_PacketIndex_Handler,
		},
		{
			MethodName: "DeviceCreate",
			Handler:    _NavzyService_DeviceCreate_Handler,
		},
		{
			MethodName: "DeviceStatusIndex",
			Handler:    _NavzyService_DeviceStatusIndex_Handler,
		},
		{
			MethodName: "DeviceImport",
			Handler:    _NavzyService_DeviceImport_Handler,
		},
		{
			MethodName: "DeviceExport",
			Handler:    _NavzyService_DeviceExport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Live",
			Handler:       _NavzyService_Live_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/services.proto",
}
