// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: services/services.proto

package services

import (
	devices "github.com/fatehan-navzy/strc/devices"
	packets "github.com/fatehan-navzy/strc/packets"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LiveStream_Task
	//	*LiveStream_Confirmation
	Payload       isLiveStream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveStream) Reset() {
	*x = LiveStream{}
	mi := &file_services_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStream) ProtoMessage() {}

func (x *LiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStream.ProtoReflect.Descriptor instead.
func (*LiveStream) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{0}
}

func (x *LiveStream) GetPayload() isLiveStream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LiveStream) GetTask() *packets.Task {
	if x != nil {
		if x, ok := x.Payload.(*LiveStream_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *LiveStream) GetConfirmation() *LiveConfirmation {
	if x != nil {
		if x, ok := x.Payload.(*LiveStream_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

type isLiveStream_Payload interface {
	isLiveStream_Payload()
}

type LiveStream_Task struct {
	Task *packets.Task `protobuf:"bytes,20,opt,name=task,proto3,oneof"`
}

type LiveStream_Confirmation struct {
	Confirmation *LiveConfirmation `protobuf:"bytes,21,opt,name=confirmation,proto3,oneof"`
}

func (*LiveStream_Task) isLiveStream_Payload() {}

func (*LiveStream_Confirmation) isLiveStream_Payload() {}

type LiveConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          uint32                 `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Received      int64                  `protobuf:"zigzag64,2,opt,name=received,proto3" json:"received,omitempty"`
	Response      int64                  `protobuf:"zigzag64,3,opt,name=response,proto3" json:"response,omitempty"`
	Confirmed     []string               `protobuf:"bytes,4,rep,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveConfirmation) Reset() {
	*x = LiveConfirmation{}
	mi := &file_services_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveConfirmation) ProtoMessage() {}

func (x *LiveConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveConfirmation.ProtoReflect.Descriptor instead.
func (*LiveConfirmation) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{1}
}

func (x *LiveConfirmation) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *LiveConfirmation) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *LiveConfirmation) GetResponse() int64 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *LiveConfirmation) GetConfirmed() []string {
	if x != nil {
		return x.Confirmed
	}
	return nil
}

type LiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynamicKeys   []string               `protobuf:"bytes,1,rep,name=dynamic_keys,proto3" json:"dynamic_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveRequest) Reset() {
	*x = LiveRequest{}
	mi := &file_services_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveRequest) ProtoMessage() {}

func (x *LiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveRequest.ProtoReflect.Descriptor instead.
func (*LiveRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{2}
}

func (x *LiveRequest) GetDynamicKeys() []string {
	if x != nil {
		return x.DynamicKeys
	}
	return nil
}

type DeviceExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       string                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceExportResponse) Reset() {
	*x = DeviceExportResponse{}
	mi := &file_services_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceExportResponse) ProtoMessage() {}

func (x *DeviceExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceExportResponse.ProtoReflect.Descriptor instead.
func (*DeviceExportResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceExportResponse) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

type DeviceExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynamicKeys   []string               `protobuf:"bytes,1,rep,name=dynamic_keys,proto3" json:"dynamic_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceExportRequest) Reset() {
	*x = DeviceExportRequest{}
	mi := &file_services_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceExportRequest) ProtoMessage() {}

func (x *DeviceExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceExportRequest.ProtoReflect.Descriptor instead.
func (*DeviceExportRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceExportRequest) GetDynamicKeys() []string {
	if x != nil {
		return x.DynamicKeys
	}
	return nil
}

type DeviceImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       string                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceImportRequest) Reset() {
	*x = DeviceImportRequest{}
	mi := &file_services_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceImportRequest) ProtoMessage() {}

func (x *DeviceImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceImportRequest.ProtoReflect.Descriptor instead.
func (*DeviceImportRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceImportRequest) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

type DeviceImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*devices.Device      `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceImportResponse) Reset() {
	*x = DeviceImportResponse{}
	mi := &file_services_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceImportResponse) ProtoMessage() {}

func (x *DeviceImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceImportResponse.ProtoReflect.Descriptor instead.
func (*DeviceImportResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceImportResponse) GetDevices() []*devices.Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynamicKeys   []string               `protobuf:"bytes,1,rep,name=dynamic_keys,json=dynamic_key,proto3" json:"dynamic_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusRequest) Reset() {
	*x = DeviceStatusRequest{}
	mi := &file_services_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusRequest) ProtoMessage() {}

func (x *DeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*DeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceStatusRequest) GetDynamicKeys() []string {
	if x != nil {
		return x.DynamicKeys
	}
	return nil
}

type DeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          uint32                 `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Records       uint32                 `protobuf:"varint,2,opt,name=records,proto3" json:"records,omitempty"`
	Items         []*DeviceStatus        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusResponse) Reset() {
	*x = DeviceStatusResponse{}
	mi := &file_services_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusResponse) ProtoMessage() {}

func (x *DeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceStatusResponse) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *DeviceStatusResponse) GetRecords() uint32 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *DeviceStatusResponse) GetItems() []*DeviceStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

type PacketRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Items         []*PacketRequest_DevicePacketRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest) Reset() {
	*x = PacketRequest{}
	mi := &file_services_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest) ProtoMessage() {}

func (x *PacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{9}
}

func (x *PacketRequest) GetItems() []*PacketRequest_DevicePacketRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type PacketResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Items         []*PacketResponse_DevicePacketResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketResponse) Reset() {
	*x = PacketResponse{}
	mi := &file_services_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketResponse) ProtoMessage() {}

func (x *PacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketResponse.ProtoReflect.Descriptor instead.
func (*PacketResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{10}
}

func (x *PacketResponse) GetItems() []*PacketResponse_DevicePacketResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type PacketRequest_DevicePacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *TimeRange             `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	DynamicKey    string                 `protobuf:"bytes,2,opt,name=dynamic_key,proto3" json:"dynamic_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest_DevicePacketRequest) Reset() {
	*x = PacketRequest_DevicePacketRequest{}
	mi := &file_services_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest_DevicePacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest_DevicePacketRequest) ProtoMessage() {}

func (x *PacketRequest_DevicePacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest_DevicePacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest_DevicePacketRequest) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{9, 0}
}

func (x *PacketRequest_DevicePacketRequest) GetFrom() *TimeRange {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PacketRequest_DevicePacketRequest) GetDynamicKey() string {
	if x != nil {
		return x.DynamicKey
	}
	return ""
}

type PacketResponse_DevicePacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynamicKey    string                 `protobuf:"bytes,1,opt,name=dynamic_key,json=dynamicKey,proto3" json:"dynamic_key,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Packets       []byte                 `protobuf:"bytes,3,opt,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketResponse_DevicePacketResponse) Reset() {
	*x = PacketResponse_DevicePacketResponse{}
	mi := &file_services_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketResponse_DevicePacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketResponse_DevicePacketResponse) ProtoMessage() {}

func (x *PacketResponse_DevicePacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketResponse_DevicePacketResponse.ProtoReflect.Descriptor instead.
func (*PacketResponse_DevicePacketResponse) Descriptor() ([]byte, []int) {
	return file_services_services_proto_rawDescGZIP(), []int{10, 0}
}

func (x *PacketResponse_DevicePacketResponse) GetDynamicKey() string {
	if x != nil {
		return x.DynamicKey
	}
	return ""
}

func (x *PacketResponse_DevicePacketResponse) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *PacketResponse_DevicePacketResponse) GetPackets() []byte {
	if x != nil {
		return x.Packets
	}
	return nil
}

var File_services_services_proto protoreflect.FileDescriptor

const file_services_services_proto_rawDesc = "" +
	"\n" +
	"\x17services/services.proto\x12\x12com.navzy.services\x1a\x13services/repo.proto\x1a\x15devices/devices.proto\x1a\x15packets/packets.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\n" +
	"LiveStream\x12-\n" +
	"\x04task\x18\x14 \x01(\v2\x17.com.navzy.packets.TaskH\x00R\x04task\x12J\n" +
	"\fconfirmation\x18\x15 \x01(\v2$.com.navzy.services.LiveConfirmationH\x00R\fconfirmationB\t\n" +
	"\apayload\"|\n" +
	"\x10LiveConfirmation\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\rR\x04cost\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x12R\breceived\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\x12R\bresponse\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x03(\tR\tconfirmed\"1\n" +
	"\vLiveRequest\x12\"\n" +
	"\fdynamic_keys\x18\x01 \x03(\tR\fdynamic_keys\"0\n" +
	"\x14DeviceExportResponse\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\"9\n" +
	"\x13DeviceExportRequest\x12\"\n" +
	"\fdynamic_keys\x18\x01 \x03(\tR\fdynamic_keys\"/\n" +
	"\x13DeviceImportRequest\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\"K\n" +
	"\x14DeviceImportResponse\x123\n" +
	"\adevices\x18\x01 \x03(\v2\x19.com.navzy.devices.DeviceR\adevices\"8\n" +
	"\x13DeviceStatusRequest\x12!\n" +
	"\fdynamic_keys\x18\x01 \x03(\tR\vdynamic_key\"|\n" +
	"\x14DeviceStatusResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\rR\x04cost\x12\x18\n" +
	"\arecords\x18\x02 \x01(\rR\arecords\x126\n" +
	"\x05items\x18\x03 \x03(\v2 .com.navzy.services.DeviceStatusR\x05items\"\xc8\x01\n" +
	"\rPacketRequest\x12K\n" +
	"\x05items\x18\x01 \x03(\v25.com.navzy.services.PacketRequest.DevicePacketRequestR\x05items\x1aj\n" +
	"\x13DevicePacketRequest\x121\n" +
	"\x04from\x18\x01 \x01(\v2\x1d.com.navzy.services.TimeRangeR\x04from\x12 \n" +
	"\vdynamic_key\x18\x02 \x01(\tR\vdynamic_key\"\xf0\x01\n" +
	"\x0ePacketResponse\x12M\n" +
	"\x05items\x18\x01 \x03(\v27.com.navzy.services.PacketResponse.DevicePacketResponseR\x05items\x1a\x8e\x01\n" +
	"\x14DevicePacketResponse\x12\x1f\n" +
	"\vdynamic_key\x18\x01 \x01(\tR\n" +
	"dynamicKey\x12;\n" +
	"\vreceived_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x18\n" +
	"\apackets\x18\x03 \x01(\fR\apackets2\xa3\x04\n" +
	"\fNavzyService\x12T\n" +
	"\vPacketIndex\x12!.com.navzy.services.PacketRequest\x1a\".com.navzy.services.PacketResponse\x12D\n" +
	"\fDeviceCreate\x12\x19.com.navzy.devices.Device\x1a\x19.com.navzy.devices.Device\x12f\n" +
	"\x11DeviceStatusIndex\x12'.com.navzy.services.DeviceStatusRequest\x1a(.com.navzy.services.DeviceStatusResponse\x12a\n" +
	"\fDeviceImport\x12'.com.navzy.services.DeviceImportRequest\x1a(.com.navzy.services.DeviceImportResponse\x12a\n" +
	"\fDeviceExport\x12'.com.navzy.services.DeviceExportRequest\x1a(.com.navzy.services.DeviceExportResponse\x12I\n" +
	"\x04Live\x12\x1f.com.navzy.services.LiveRequest\x1a\x1e.com.navzy.services.LiveStream0\x01BF\n" +
	"\x1acom.fatehan.navzy.servicesP\x01Z&github.com/fatehan-navzy/strc/servicesb\x06proto3"

var (
	file_services_services_proto_rawDescOnce sync.Once
	file_services_services_proto_rawDescData []byte
)

func file_services_services_proto_rawDescGZIP() []byte {
	file_services_services_proto_rawDescOnce.Do(func() {
		file_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_services_proto_rawDesc), len(file_services_services_proto_rawDesc)))
	})
	return file_services_services_proto_rawDescData
}

var file_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_services_proto_goTypes = []any{
	(*LiveStream)(nil),                          // 0: com.navzy.services.LiveStream
	(*LiveConfirmation)(nil),                    // 1: com.navzy.services.LiveConfirmation
	(*LiveRequest)(nil),                         // 2: com.navzy.services.LiveRequest
	(*DeviceExportResponse)(nil),                // 3: com.navzy.services.DeviceExportResponse
	(*DeviceExportRequest)(nil),                 // 4: com.navzy.services.DeviceExportRequest
	(*DeviceImportRequest)(nil),                 // 5: com.navzy.services.DeviceImportRequest
	(*DeviceImportResponse)(nil),                // 6: com.navzy.services.DeviceImportResponse
	(*DeviceStatusRequest)(nil),                 // 7: com.navzy.services.DeviceStatusRequest
	(*DeviceStatusResponse)(nil),                // 8: com.navzy.services.DeviceStatusResponse
	(*PacketRequest)(nil),                       // 9: com.navzy.services.PacketRequest
	(*PacketResponse)(nil),                      // 10: com.navzy.services.PacketResponse
	(*PacketRequest_DevicePacketRequest)(nil),   // 11: com.navzy.services.PacketRequest.DevicePacketRequest
	(*PacketResponse_DevicePacketResponse)(nil), // 12: com.navzy.services.PacketResponse.DevicePacketResponse
	(*packets.Task)(nil),                        // 13: com.navzy.packets.Task
	(*devices.Device)(nil),                      // 14: com.navzy.devices.Device
	(*DeviceStatus)(nil),                        // 15: com.navzy.services.DeviceStatus
	(*TimeRange)(nil),                           // 16: com.navzy.services.TimeRange
	(*timestamppb.Timestamp)(nil),               // 17: google.protobuf.Timestamp
}
var file_services_services_proto_depIdxs = []int32{
	13, // 0: com.navzy.services.LiveStream.task:type_name -> com.navzy.packets.Task
	1,  // 1: com.navzy.services.LiveStream.confirmation:type_name -> com.navzy.services.LiveConfirmation
	14, // 2: com.navzy.services.DeviceImportResponse.devices:type_name -> com.navzy.devices.Device
	15, // 3: com.navzy.services.DeviceStatusResponse.items:type_name -> com.navzy.services.DeviceStatus
	11, // 4: com.navzy.services.PacketRequest.items:type_name -> com.navzy.services.PacketRequest.DevicePacketRequest
	12, // 5: com.navzy.services.PacketResponse.items:type_name -> com.navzy.services.PacketResponse.DevicePacketResponse
	16, // 6: com.navzy.services.PacketRequest.DevicePacketRequest.from:type_name -> com.navzy.services.TimeRange
	17, // 7: com.navzy.services.PacketResponse.DevicePacketResponse.received_at:type_name -> google.protobuf.Timestamp
	9,  // 8: com.navzy.services.NavzyService.PacketIndex:input_type -> com.navzy.services.PacketRequest
	14, // 9: com.navzy.services.NavzyService.DeviceCreate:input_type -> com.navzy.devices.Device
	7,  // 10: com.navzy.services.NavzyService.DeviceStatusIndex:input_type -> com.navzy.services.DeviceStatusRequest
	5,  // 11: com.navzy.services.NavzyService.DeviceImport:input_type -> com.navzy.services.DeviceImportRequest
	4,  // 12: com.navzy.services.NavzyService.DeviceExport:input_type -> com.navzy.services.DeviceExportRequest
	2,  // 13: com.navzy.services.NavzyService.Live:input_type -> com.navzy.services.LiveRequest
	10, // 14: com.navzy.services.NavzyService.PacketIndex:output_type -> com.navzy.services.PacketResponse
	14, // 15: com.navzy.services.NavzyService.DeviceCreate:output_type -> com.navzy.devices.Device
	8,  // 16: com.navzy.services.NavzyService.DeviceStatusIndex:output_type -> com.navzy.services.DeviceStatusResponse
	6,  // 17: com.navzy.services.NavzyService.DeviceImport:output_type -> com.navzy.services.DeviceImportResponse
	3,  // 18: com.navzy.services.NavzyService.DeviceExport:output_type -> com.navzy.services.DeviceExportResponse
	0,  // 19: com.navzy.services.NavzyService.Live:output_type -> com.navzy.services.LiveStream
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_services_proto_init() }
func file_services_services_proto_init() {
	if File_services_services_proto != nil {
		return
	}
	file_services_repo_proto_init()
	file_services_services_proto_msgTypes[0].OneofWrappers = []any{
		(*LiveStream_Task)(nil),
		(*LiveStream_Confirmation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_services_proto_rawDesc), len(file_services_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_services_proto_goTypes,
		DependencyIndexes: file_services_services_proto_depIdxs,
		MessageInfos:      file_services_services_proto_msgTypes,
	}.Build()
	File_services_services_proto = out.File
	file_services_services_proto_goTypes = nil
	file_services_services_proto_depIdxs = nil
}
