// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: devices/devices.proto

package devices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device_ProtocolEnum int32

const (
	Device_Unknown          Device_ProtocolEnum = 0
	Device_Teltonika_FMB920 Device_ProtocolEnum = 1
)

// Enum value maps for Device_ProtocolEnum.
var (
	Device_ProtocolEnum_name = map[int32]string{
		0: "Unknown",
		1: "Teltonika_FMB920",
	}
	Device_ProtocolEnum_value = map[string]int32{
		"Unknown":          0,
		"Teltonika_FMB920": 1,
	}
)

func (x Device_ProtocolEnum) Enum() *Device_ProtocolEnum {
	p := new(Device_ProtocolEnum)
	*p = x
	return p
}

func (x Device_ProtocolEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Device_ProtocolEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_devices_proto_enumTypes[0].Descriptor()
}

func (Device_ProtocolEnum) Type() protoreflect.EnumType {
	return &file_devices_devices_proto_enumTypes[0]
}

func (x Device_ProtocolEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Device_ProtocolEnum.Descriptor instead.
func (Device_ProtocolEnum) EnumDescriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{1, 0}
}

type Device_StatEnum int32

const (
	Device_Pending   Device_StatEnum = 0
	Device_Active    Device_StatEnum = 1
	Device_Moved     Device_StatEnum = 2
	Device_Suspended Device_StatEnum = 3
)

// Enum value maps for Device_StatEnum.
var (
	Device_StatEnum_name = map[int32]string{
		0: "Pending",
		1: "Active",
		2: "Moved",
		3: "Suspended",
	}
	Device_StatEnum_value = map[string]int32{
		"Pending":   0,
		"Active":    1,
		"Moved":     2,
		"Suspended": 3,
	}
)

func (x Device_StatEnum) Enum() *Device_StatEnum {
	p := new(Device_StatEnum)
	*p = x
	return p
}

func (x Device_StatEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Device_StatEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_devices_proto_enumTypes[1].Descriptor()
}

func (Device_StatEnum) Type() protoreflect.EnumType {
	return &file_devices_devices_proto_enumTypes[1]
}

func (x Device_StatEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Device_StatEnum.Descriptor instead.
func (Device_StatEnum) EnumDescriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{1, 1}
}

type ProtocolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProtocolList_Item   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolList) Reset() {
	*x = ProtocolList{}
	mi := &file_devices_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolList) ProtoMessage() {}

func (x *ProtocolList) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolList.ProtoReflect.Descriptor instead.
func (*ProtocolList) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolList) GetList() []*ProtocolList_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DynamicKey    string                 `protobuf:"bytes,2,opt,name=dynamic_key,json=dynamicKey,proto3" json:"dynamic_key,omitempty"`
	StaticKey     string                 `protobuf:"bytes,3,opt,name=static_key,json=staticKey,proto3" json:"static_key,omitempty"`
	Imei          uint64                 `protobuf:"varint,4,opt,name=imei,proto3" json:"imei,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Stat          Device_StatEnum        `protobuf:"varint,6,opt,name=stat,proto3,enum=com.navzy.devices.Device_StatEnum" json:"stat,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Protocol      Device_ProtocolEnum    `protobuf:"varint,8,opt,name=protocol,proto3,enum=com.navzy.devices.Device_ProtocolEnum" json:"protocol,omitempty"`
	Timezone      int32                  `protobuf:"zigzag32,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_devices_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetDynamicKey() string {
	if x != nil {
		return x.DynamicKey
	}
	return ""
}

func (x *Device) GetStaticKey() string {
	if x != nil {
		return x.StaticKey
	}
	return ""
}

func (x *Device) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *Device) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Device) GetStat() Device_StatEnum {
	if x != nil {
		return x.Stat
	}
	return Device_Pending
}

func (x *Device) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Device) GetProtocol() Device_ProtocolEnum {
	if x != nil {
		return x.Protocol
	}
	return Device_Unknown
}

func (x *Device) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProtocolList_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      int32                  `protobuf:"zigzag32,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolList_Item) Reset() {
	*x = ProtocolList_Item{}
	mi := &file_devices_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolList_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolList_Item) ProtoMessage() {}

func (x *ProtocolList_Item) ProtoReflect() protoreflect.Message {
	mi := &file_devices_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolList_Item.ProtoReflect.Descriptor instead.
func (*ProtocolList_Item) Descriptor() ([]byte, []int) {
	return file_devices_devices_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtocolList_Item) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ProtocolList_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_devices_devices_proto protoreflect.FileDescriptor

const file_devices_devices_proto_rawDesc = "" +
	"\n" +
	"\x15devices/devices.proto\x12\x11com.navzy.devices\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\fProtocolList\x128\n" +
	"\x04list\x18\x01 \x03(\v2$.com.navzy.devices.ProtocolList.ItemR\x04list\x1a6\n" +
	"\x04Item\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\x11R\bprotocol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x04\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdynamic_key\x18\x02 \x01(\tR\n" +
	"dynamicKey\x12\x1d\n" +
	"\n" +
	"static_key\x18\x03 \x01(\tR\tstaticKey\x12\x12\n" +
	"\x04imei\x18\x04 \x01(\x04R\x04imei\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x126\n" +
	"\x04stat\x18\x06 \x01(\x0e2\".com.navzy.devices.Device.StatEnumR\x04stat\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12B\n" +
	"\bprotocol\x18\b \x01(\x0e2&.com.navzy.devices.Device.ProtocolEnumR\bprotocol\x12\x1a\n" +
	"\btimezone\x18\t \x01(\x11R\btimezone\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"1\n" +
	"\fProtocolEnum\x12\v\n" +
	"\aUnknown\x10\x00\x12\x14\n" +
	"\x10Teltonika_FMB920\x10\x01\"=\n" +
	"\bStatEnum\x12\v\n" +
	"\aPending\x10\x00\x12\n" +
	"\n" +
	"\x06Active\x10\x01\x12\t\n" +
	"\x05Moved\x10\x02\x12\r\n" +
	"\tSuspended\x10\x03BD\n" +
	"\x19com.fatehan.navzy.devicesP\x01Z%github.com/fatehan-navzy/strc/devicesb\x06proto3"

var (
	file_devices_devices_proto_rawDescOnce sync.Once
	file_devices_devices_proto_rawDescData []byte
)

func file_devices_devices_proto_rawDescGZIP() []byte {
	file_devices_devices_proto_rawDescOnce.Do(func() {
		file_devices_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devices_devices_proto_rawDesc), len(file_devices_devices_proto_rawDesc)))
	})
	return file_devices_devices_proto_rawDescData
}

var file_devices_devices_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_devices_devices_proto_goTypes = []any{
	(Device_ProtocolEnum)(0),      // 0: com.navzy.devices.Device.ProtocolEnum
	(Device_StatEnum)(0),          // 1: com.navzy.devices.Device.StatEnum
	(*ProtocolList)(nil),          // 2: com.navzy.devices.ProtocolList
	(*Device)(nil),                // 3: com.navzy.devices.Device
	(*ProtocolList_Item)(nil),     // 4: com.navzy.devices.ProtocolList.Item
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_devices_devices_proto_depIdxs = []int32{
	4, // 0: com.navzy.devices.ProtocolList.list:type_name -> com.navzy.devices.ProtocolList.Item
	1, // 1: com.navzy.devices.Device.stat:type_name -> com.navzy.devices.Device.StatEnum
	0, // 2: com.navzy.devices.Device.protocol:type_name -> com.navzy.devices.Device.ProtocolEnum
	5, // 3: com.navzy.devices.Device.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: com.navzy.devices.Device.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_devices_devices_proto_init() }
func file_devices_devices_proto_init() {
	if File_devices_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devices_devices_proto_rawDesc), len(file_devices_devices_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_devices_devices_proto_goTypes,
		DependencyIndexes: file_devices_devices_proto_depIdxs,
		EnumInfos:         file_devices_devices_proto_enumTypes,
		MessageInfos:      file_devices_devices_proto_msgTypes,
	}.Build()
	File_devices_devices_proto = out.File
	file_devices_devices_proto_goTypes = nil
	file_devices_devices_proto_depIdxs = nil
}
