// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: devices/devices.proto

package devices

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProtocolList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProtocolList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProtocolList with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProtocolListMultiError, or
// nil if none found.
func (m *ProtocolList) ValidateAll() error {
	return m.validate(true)
}

func (m *ProtocolList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProtocolListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProtocolListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProtocolListValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProtocolListMultiError(errors)
	}

	return nil
}

// ProtocolListMultiError is an error wrapping multiple validation errors
// returned by ProtocolList.ValidateAll() if the designated constraints aren't met.
type ProtocolListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProtocolListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProtocolListMultiError) AllErrors() []error { return m }

// ProtocolListValidationError is the validation error returned by
// ProtocolList.Validate if the designated constraints aren't met.
type ProtocolListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProtocolListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProtocolListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProtocolListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProtocolListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProtocolListValidationError) ErrorName() string { return "ProtocolListValidationError" }

// Error satisfies the builtin error interface
func (e ProtocolListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProtocolList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProtocolListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProtocolListValidationError{}

// Validate checks the field values on Device with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Device) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Device with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DeviceMultiError, or nil if none found.
func (m *Device) ValidateAll() error {
	return m.validate(true)
}

func (m *Device) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DynamicKey

	// no validation rules for StaticKey

	if val := m.GetImei(); val < 100000000000000 || val > 999999999999999 {
		err := DeviceValidationError{
			field:  "Imei",
			reason: "value must be inside range [100000000000000, 999999999999999]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPort() != 0 {

		if val := m.GetPort(); val < 1 || val > 65535 {
			err := DeviceValidationError{
				field:  "Port",
				reason: "value must be inside range [1, 65535]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if _, ok := Device_StatEnum_name[int32(m.GetStat())]; !ok {
		err := DeviceValidationError{
			field:  "Stat",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTitle()); l < 3 || l > 255 {
		err := DeviceValidationError{
			field:  "Title",
			reason: "value length must be between 3 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _Device_Protocol_NotInLookup[m.GetProtocol()]; ok {
		err := DeviceValidationError{
			field:  "Protocol",
			reason: "value must not be in list [Unknown]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetTimezone(); val < -14 || val > 14 {
		err := DeviceValidationError{
			field:  "Timezone",
			reason: "value must be inside range [-14, 14]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeviceMultiError(errors)
	}

	return nil
}

// DeviceMultiError is an error wrapping multiple validation errors returned by
// Device.ValidateAll() if the designated constraints aren't met.
type DeviceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceMultiError) AllErrors() []error { return m }

// DeviceValidationError is the validation error returned by Device.Validate if
// the designated constraints aren't met.
type DeviceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceValidationError) ErrorName() string { return "DeviceValidationError" }

// Error satisfies the builtin error interface
func (e DeviceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDevice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceValidationError{}

var _Device_Protocol_NotInLookup = map[Device_ProtocolEnum]struct{}{
	0: {},
}

// Validate checks the field values on ProtocolList_Item with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProtocolList_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProtocolList_Item with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProtocolList_ItemMultiError, or nil if none found.
func (m *ProtocolList_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *ProtocolList_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Protocol

	// no validation rules for Name

	if len(errors) > 0 {
		return ProtocolList_ItemMultiError(errors)
	}

	return nil
}

// ProtocolList_ItemMultiError is an error wrapping multiple validation errors
// returned by ProtocolList_Item.ValidateAll() if the designated constraints
// aren't met.
type ProtocolList_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProtocolList_ItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProtocolList_ItemMultiError) AllErrors() []error { return m }

// ProtocolList_ItemValidationError is the validation error returned by
// ProtocolList_Item.Validate if the designated constraints aren't met.
type ProtocolList_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProtocolList_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProtocolList_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProtocolList_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProtocolList_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProtocolList_ItemValidationError) ErrorName() string {
	return "ProtocolList_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e ProtocolList_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProtocolList_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProtocolList_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProtocolList_ItemValidationError{}
